version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI at http://localhost:15672 (user: guest, pass: guest)

  user_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: python services/user_services.py
    depends_on:
      - rabbitmq
    ports:
      - "5001:5001"

  product_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: python services/product_service.py
    depends_on:
      - rabbitmq
    ports:
      - "5002:5002"

  order_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: python services/order_service.py
    depends_on:
      - rabbitmq
    ports:
      - "5003:5003"

  provider_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: python services/provider_service.py
    ports:
      - "5010:5010"

  receipt_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: python services/receipt_service.py
    ports:
      - "5011:5011"

  payment_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: python services/payment_service.py
    depends_on:
      - rabbitmq
    ports:
      - "5004:5004"

  notification_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: python services/notification_service.py
    depends_on:
      - rabbitmq

  order_aggregation_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: python services/order_aggregation_service.py
    depends_on:
      - rabbitmq
    ports:
      - "5006:5006"

  report_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: python services/report_service.py
    depends_on:
      - rabbitmq