version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI at http://localhost:15672 (user: guest, pass: guest)

  user_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: python services/user_services.py
    depends_on:
      - rabbitmq
    ports:
      - "5001:5001"

  product_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: python services/product_service.py
    depends_on:
      - rabbitmq
    ports:
      - "5002:5002"

  order_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: python services/order_service.py
    depends_on:
      - rabbitmq
    ports:
      - "5003:5003"

  payment_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: python services/payment_service.py
    depends_on:
      - rabbitmq
    ports:
      - "5004:5004"

  notification_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: python services/notification_service.py
    depends_on:
      - rabbitmq

# Add more services as needed